### ISSUE TITLE
fatal error: camera_info_manager/camera_info_manager.hpp: No such file or directory

### ISSUE THREAD

**Issue by samuk** [ros-perception/image_common#250]
22.04 - Humble. Trying to compile https://github.com/surfertas/ros2_ipcamera
I raised my issue there too: https://github.com/surfertas/ros2_ipcamera/issues/15

ros-humble-camera-info-manager is already the newest version (3.1.4-2jammy.20220620.220336).

In file included from /home/ubuntu/atom_matrix_ros2-main/linorobot2_esp32_ws/src/ros2_ipcamera/src/ipcamera_component.cpp:20:
/home/ubuntu/atom_matrix_ros2-main/linorobot2_esp32_ws/src/ros2_ipcamera/include/ros2_ipcamera/ipcamera_component.hpp:24:10: fatal error: camera_info_manager/camera_info_manager.hpp: No such file or directory
   24 | #include <camera_info_manager/camera_info_manager.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

What can I try or what further info can I provide please?

**Comment by gbiggs** [comment]
The repository you linked to has not been updated since September 2020, at which time the latest ROS 2 distribution was Foxy. I think it is unlikely it would work with Humble or on Ubuntu 22.04. I was able to compile the `foxy` and `master` branches successfully on ROS 2 Foxy. If you want to use it, I think that you will need to either find the maintainer and convince them to update it, or do that work yourself and submit a PR.
