### PR TITLE
[ros2] add missing set header

### PR DESCRIPTION
**Pull request by mikaelarguedas**
WIthout this it fails to compile on gcc 9.2 with the following:

```
/tmp/demo_deps_ws/src/image_common/image_transport/src/publisher.cpp:111:8: error: ‘set’ is not a member of ‘std’
  111 |   std::set<std::string> blacklist;
      |        ^~~
/tmp/demo_deps_ws/src/image_common/image_transport/src/publisher.cpp:44:1: note: ‘std::set’ is defined in header ‘<set>’; did you forget to ‘#include <set>’?
```

cc @mjcarroll 

Signed-off-by: Mikael Arguedas <mikael.arguedas@gmail.com>

### CODE REVIEW

**Review by mjcarroll — APPROVED** [review]
LGTM, thanks for living on the edge :)

**Comment by galou** [comment]
Shouldn't this be back-ported to the `dashing` branch?
